#ifndef __ERRORCODES_H__
#define __ERRORCODES_H__



#define FILE_DOESNT_EXIST 404
#define RECIEVE_COMMAND_ERROR 402
#define SEND_COMMAND_ERROR 400
#define STRUCT_RECEIVE_ERROR 406
#define EXECUTE_COMMAND_ERROR 500
#define RECIEVE_ERROR 501
#define ACK_SEND_ERROR 502
#define NAMING_SERVER_OFFLINE 503
#define CONNECTION_ERROR 504
#define ACK_RECIEVE_ERROR_SS 505
#define SS_TO_NS_CONNECTION_ERROR 506
#define INIT_SERVER_ERROR 507
#define SS_INSTRUCTION_FORWARD_ERROR 550
#define SS_CREATE_ERROR 551
#define UNSUCCESSFUL_CLIENT_TO_SS_CONNECT 564
#define UNSUCCESSFUL_SS_CONNECT 552
#define UNSUCCESSFUL_CLIENT_CONNECT 553
#define INCOMPLETE_CLIENT_DATA 554
#define CLIENT_PORT_ASSIGN_ERROR 555
#define NS_PORT_ASSIGN_ERROR 556
#define INITIALISE_SERVER_ERROR 557
#define PORT_NOT_FOUND 558
#define NOT_FOUND_DELETE 559
#define READ_ERROR 560
#define WRITE_ERROR 561
#define INFO_ERROR 562
#define READ_SEND_ERROR 563
#define STRUCT_SEND_ERROR 565



#endif